name: nasa_flutter
description: "NASA's Astronomy Picture of the Day - Flutter version."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  dio: ^5.4.3+1
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: # Version from hive
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon.png"
  android: true
  ios: true
